# Generated by Django 5.1.7 on 2025-06-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_profile_image_profile_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
    ]
